[package]
name = "classicalang"
version = "0.1.0"
edition = "2021"

[dependencies]
combine = "4.6.6"
quickcheck = "1.0.3"
quickcheck_macros = "1"
pretty = "0.12.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
